# Generated by Django 3.0.3 on 2020-04-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200430_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-amount']},
        ),
    ]
