# Generated by Django 3.0.3 on 2020-04-30 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='welcome_message',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
