# Generated by Django 3.0.3 on 2020-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200430_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
